# ruff: noqa: E402 — env vars must be set before numpy/pymc imports

"""Posited model (what gets FIT to data generated by generate_data.py).

    y_ig ~ N(s(x_ig) + mu_g, sigma^2)
    mu_g ~ N(mu0, tau^2)
    mu0  ~ N(0, 1)
    lam  ~ Exp(5)          # smoothing (regularization) parameter for s(x)
    sigma, tau ~ Exp(1)

s(x) is a penalized regression spline of basis dimension k (the "spline
basis dimension" from the paper -- e.g. 6, 12, 24, 48). Penalization is
implemented the standard P-spline way: the k spline coefficients follow a
1st-order random walk whose innovation SD is governed by lam. Larger lam
-> smaller innovation variance -> smoother/more constrained fit. This is
the conventional way "lambda ~ Exp(5)" cashes out as an actual prior on
spline coefficients in a Bayesian GAM.

IDENTIFIABILITY FIX (sum-to-zero constraint on s(x)):
Previously, mu0 (the population mean of the mu_g's) was confounded with
the overall vertical level of s(x) -- nothing pinned down "where the
spline's baseline sits" vs. "what the average group offset is". The
standard remedy (used in mgcv and most Bayesian GAM implementations) is to
constrain the smooth term to average zero over the observed data:

    sum_i s(x_i) = 0

This is implemented below by centering the deterministic spline output at
every posterior draw: s_x_centered = s_x - mean(s_x). That removes the
smooth term's one shared degree of freedom in the vertical direction,
leaving mu0 (and the mu_g's) as the sole carriers of overall level --
the standard GAM identifiability constraint, with no change needed to the
random-walk penalty structure on beta.

NOTE: k is a property of this fitted model only, never of the DGP
(see generate_data.py, which has no k parameter at all).
"""

from functools import partial
import os
from pathlib import Path
import sys
import warnings

# ── Runtime path & environment setup ─────────────────────────────────────
# These must happen BEFORE third-party imports (numpy, scipy, pymc) because
# those libraries read OMP/BLAS env vars at import time. The sys.path
# insert also needs to happen early so that 'calibration_simulations' and
# 'compressor_fouling_modeling' resolve correctly when run as a script.
_project_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_project_root))

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

CALIB_SIM_DIR = _project_root / "calibration_simulations"
DIAGNOSTICS_DIR = CALIB_SIM_DIR / "diagnostics"
DIAGNOSTICS_DIR.mkdir(parents=True, exist_ok=True)
CALIB_SIM_RES_DIR = CALIB_SIM_DIR / "simulation_results"
CALIB_SIM_RES_DIR.mkdir(parents=True, exist_ok=True)

# Third-party imports
from typing import cast

import arviz_plots as azp
from arviz_stats.loo import loo
from arviz_stats.loo.helper_loo import (
    _warn_pareto_k,  # ruff: ignore[import-private-name]
)
from arviz_stats.loo.loo_expectations import loo_expectations
from arviz_stats.summary import summary
from arviz_stats.utils import ELPDData
from arviz_stats.visualization import hdi
from joblib import Parallel, delayed
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from patsy.highlevel import dmatrix
import pymc as pm
from tqdm import tqdm
from xarray import DataArray, DataTree

# Local imports
from calibration_simulations.generate_data import DGPParams, generate_dataset
from calibration_simulations.utility import (
    CalibrationResult,
    FittedModel,
    InhibitSleep,
    LogTime,
    LooDiagnostics,
    LpvStats,
    ModelDims,
    ModelFit,
    SimulationResult,
    UniformityStats,
    compute_loo_pit_uniformity_stats,
    entropy_uniformity_z_score,
    plot_pit_hist,
)
from compressor_fouling_modeling.utility import (
    _create_loo_pit_plot,  # ruff: ignore[import-private-name] #pyright: ignore[reportPrivateUsage]
    _render_pc_to_img,  # ruff: ignore[import-private-name] #pyright: ignore[reportPrivateUsage]
    _resolve_likelihood_var_name,  # ruff: ignore[import-private-name] #pyright: ignore[reportPrivateUsage]
    plot_loo_calibration_curve_with_reference,
)


def build_spline_basis(x: np.ndarray, k: int, degree: int = 3) -> np.ndarray:
    """Build a cubic B-spline design matrix with exactly k basis columns.

    The basis has no separate intercept column because the model intercept is
    carried by the group-level `mu_g` prior instead of the spline itself.

    Args:
      x: The predictor values on which to evaluate the basis.
      k: Number of basis columns in the design matrix.
      degree: Polynomial degree of the spline basis. Defaults to 3.

    Returns:
      The B-spline design matrix with shape (len(x), k).

    Example:
      ```python
      import numpy as np
      from calibration_simulations.fit_model import build_spline_basis

      x = np.linspace(0, 1, 50)
      basis = build_spline_basis(x, k=8)
      ```

    """
    formula = f"bs(x, df={k}, degree={degree}, include_intercept=True) - 1"
    B = dmatrix(formula, {"x": x}, return_type="dataframe")
    return np.asarray(B)


def _add_data_containers(
    model: pm.Model, df: pd.DataFrame, B: np.ndarray, group_idx: np.ndarray
):
    """Register the model's mutable data containers as pm.Data variables.

    The registered containers are shared between the model and the sampler so
    that covariates and outcomes can be updated across iterations.

    Args:
        model: The PyMC model in which to register the containers.
        df: DataFrame containing the observed outcome column.
        B: Covariate matrix to register as data.
        group_idx: Group index array to register as data.

    Returns:
        A tuple (B_data, group_idx_data, y_data), where B_data is the
        registered covariate container, group_idx_data is the registered
        group index container, and y_data is the registered outcome container.

    Example:
        >>> import pymc as pm
        >>> _ = pm.Model()
        >>> B, group_idx = np.eye(3), np.array([0, 1, 1])
        >>> df = pd.DataFrame({"y": [1.0, 2.0, 3.0]})
        >>> B_data, group_idx_data, y_data = _add_data_containers(
        ...     pm.Model(), df, B, group_idx
        ... )

    """
    with model:
        B_data = pm.Data("B", B)
        group_idx_data = pm.Data("group_idx", group_idx)
        y_data = pm.Data("y_obs_data", df["y"].to_numpy())
    return B_data, group_idx_data, y_data


def _add_group_effects(model: pm.Model):
    """Add the hierarchical group-level random intercepts.

    `mu0` (the global intercept hyperprior) and `tau` (the group-effect
    scale) are registered on the model but not returned, since only the
    per-group intercepts `mu_g` are needed downstream.

    Args:
        model: The PyMC model in which to add the group effects.

    Returns:
        The per-group intercepts random variable `mu_g`.

    Example:
        >>> import pymc as pm
        >>> model = pm.Model()
        >>> mu_g = _add_group_effects(model)

    """
    with model:
        tau = pm.Exponential("tau", 1)
        mu0 = pm.Normal("mu0", 0, 1)
        mu_g = pm.Normal("mu_g", mu=mu0, sigma=tau, dims="group")
    return mu_g  # ruff: ignore[unnecessary-assign]


def _add_spline_coefficients(model: pm.Model):
    """Add the non-centered, penalised random-walk spline coefficients.

    Non-centered parameterization avoids Neal's funnel: `beta`'s scale
    depends on `lam` (via `innov_sd`), which creates pathological geometry
    if sampled directly. Instead we sample unit-scale, lam-independent
    normals and apply the lam-dependent scaling as a deterministic
    transform afterward.

    Args:
        model: The PyMC model in which to add the spline coefficients.

    Returns:
        The deterministic random-walk spline coefficients `beta`.

    Example:
        >>> import pymc as pm
        >>> model = pm.Model()
        >>> beta = _add_spline_coefficients(model)

    """
    with model:
        # smoothing (regularization) parameter for the spline;
        # Gamma(2, 0.4) has mode ~2.5, keeping innov_sd ~ 0.6 typical,
        # with little mass near zero to avoid explosive random walks
        lam = pm.Gamma("lam", alpha=2, beta=0.4)
        # penalized spline coefficients: 1st-order random walk, innovation SD
        # tied to the smoothing parameter lam (larger `λ` shrinks adjacent
        # coefficients together → smoother fit)
        # NON-CENTERED parameterization to avoid Neal's funnel: beta's
        # scale depends on lam (via innov_sd), which creates a pathological
        # geometry when sampled directly (centered form) -- NUTS can't use
        # one step size for both the "wide" (small lam) and "narrow"
        # (large lam) regimes. Instead we sample unit-scale, lam-independent
        # normals and apply the lam-dependent scaling as a deterministic
        # transform afterward.
        innov_sd = 1.0 / pm.math.sqrt(lam)  # pyright: ignore[reportOperatorIssue]
        # the starting coefficinet (no penalty on \beta0)
        beta0 = pm.Normal("beta0", 0, 1)
        # k-1 independent standard normals (one per basis after the first)
        beta_innov_raw = pm.Normal("beta_innov_raw", 0, 1, dims="basis_innov")
        # scale each innovation by 1/\sqrt(lam))
        beta_innov = beta_innov_raw * innov_sd
        # prepend a zero so cumsum produces k element
        increments = pm.math.concatenate([[0.0], beta_innov])
        # \beta_j = \beta_0 + \sum_{i=1}^{j} \varepsilon_i, \quad \varepsilon_i
        # \sim \mathcal{N}(0, 1 / \sqrt{\lambda})
        beta = pm.Deterministic(
            "beta", beta0 + pm.math.cumsum(increments), dims="basis"
        )
    return beta  # ruff: ignore[unnecessary-assign]


def _add_smooth_term(model: pm.Model, B_data, beta):  # pyright: ignore[reportMissingParameterType]
    """Compute the sum-to-zero-constrained smooth term B @ beta.

    Args:
        model: The PyMC model in which to add the smooth term.
        B_data: Covariate basis matrix for the smooth.
        beta: Spline coefficients used in the linear predictor.

    Returns:
        The mean-centered deterministic smooth term `s_x`.

    Example:
        >>> import pymc as pm
        >>> model = pm.Model()
        >>> s_x = _add_smooth_term(model, B_data, beta)

    """
    with model:
        # linear predictor B @ beta
        s_x_raw = pm.math.dot(B_data, beta)
        s_x = pm.Deterministic("s_x", s_x_raw - pm.math.mean(s_x_raw))
        # the identifiability sum-to-zero constraint: center the smooth term
        # over the observed data to resolve the mu0/level confound. mu0 no later
        # estimates the population mean of the true mu_g but mean of (mu_g +
        # f(x))
    return s_x  # ruff: ignore[unnecessary-assign]


def build_model(df: pd.DataFrame, k: int) -> pm.Model:
    r"""Build a hierarchical Bayesian P-spline model with group-level intercepts.

    Constructs a first-order random-walk penalised B-spline (P-spline) with
    group-specific random intercepts. The smoothing parameter `lam` controls the
    innovation SD of the random walk on the spline coefficients, encoding a
    discrete penalty on first differences. This is the Bayesian analogue of the
    classical P-spline penalty :math:`\\lambda \\sum_{j=2}^{k} (\beta_j -
    \beta_{j-1})^2`, where the Gaussian random walk prior :math:`\beta_j -
    \beta_{j-1} \\sim \\mathcal{N}(0, 1/\\lambda)` induces the same quadratic
    penalty in the log-posterior. A sum-to-zero constraint on the smooth term
    ensures identifiability with the group intercepts.

    Args:
        df: DataFrame with columns 'x' (covariate), 'y' (response), and
            'group' (categorical grouping variable). Typically generated by
            :func:`generate_dataset`.
        k: Number of B-spline basis functions for the fitted model. Need not
            match the dimension used in the data-generating process.

    Returns:
        A compiled-uncompiled PyMC model object with coordinates 'basis' and
        'group'.

    Example:
        >>> import pandas as pd
        >>> df = pd.DataFrame(
        ...     {
        ...         "x": np.linspace(0, 1, 50),
        ...         "y": np.sin(2 * np.pi * np.linspace(0, 1, 50)),
        ...         "group": ["a"] * 25 + ["b"] * 25,
        ...     }
        ... )
        >>> model = build_model(df, k=10)
        >>> isinstance(model, pm.Model)
        True

    """
    group_idx, group_labels = df["group"].factorize()
    B = build_spline_basis(df["x"].to_numpy(), k=k)  # (G * N, k)

    model = pm.Model(
        coords={
            "basis": np.arange(k),
            "basis_innov": np.arange(k - 1),
            "group": group_labels,
            "obs": np.arange(len(df["y"])),
        }
    )

    B_data, group_idx_data, y_data = _add_data_containers(model, df, B, group_idx)
    mu_g = _add_group_effects(model)
    beta = _add_spline_coefficients(model)
    s_x = _add_smooth_term(model, B_data, beta)

    with model:
        sigma = pm.Exponential("sigma", 1)
        _ = pm.Normal(
            "y_obs",
            mu=s_x + mu_g[group_idx_data],
            sigma=sigma,
            observed=y_data,
            shape=df.shape[0],
            dims="obs",
        )

    return model


def plot_fit_quality_check(
    df: pd.DataFrame,
    idata: DataTree,
    k: int,
    m: int,
    loo_r2: str,
    save_path: Path,
) -> None:
    """Plot posterior fitted curve against observed data and true function.

    Compares the posterior mean of the population-level fit (s(x) + mu0) to
    the true underlying function f_true, with a 95% credible band. Used to
    visually assess how well the spline-based model recovers the true signal
    under different basis dimensions k and smoothness parameters m.

    Args:
      df: DataFrame with columns ``'x'``, ``'y'``, and ``'f_true'``.
      idata: InferenceData object containing posterior ``'s_x'`` and ``'mu0'``.
      k: Spline basis dimension used in the fitted model.
      m: True smoothness parameter from the data-generating process.
      loo_r2: mean and hdi lower and upper bounds of Loo-adjustd R2.
      save_path: Path to save the resulting figure.

    Example:
      >>> from calibration_simulations.generate_data import (
      ...     DGPParams,
      ...     generate_dataset,
      ... )
      >>> import pymc as pm
      >>> params = DGPParams(G=50, m=5, sigma=0.1)
      >>> df = generate_dataset(params, np.random.default_rng(42))
      >>> model = build_model(df, k=12)
      >>> with model:
      ...     idata = pm.sample(draws=500, tune=500, chains=2)
      >>> plot_fit_quality_check(df, idata, 12, 5, loo_r2, save_path)

    """
    x = df["x"].to_numpy()
    order = np.argsort(x)
    s_x_post = idata.posterior["s_x"]
    mu0_post = idata.posterior["mu0"]
    fitted_curve = (s_x_post + mu0_post).stack(sample=("chain", "draw"))  # noqa: PD013 - stack() required for xarray dimension stacking
    fitted_mean = fitted_curve.mean("sample").to_numpy()
    fitted_lo = fitted_curve.quantile(0.025, dim="sample").to_numpy()
    fitted_hi = fitted_curve.quantile(0.975, dim="sample").to_numpy()

    fig, ax = plt.subplots(figsize=(7, 4))
    _ = ax.scatter(x, df["y"], s=10, alpha=0.3, label="observed y")
    _ = ax.plot(
        x[order], df["f_true"].to_numpy()[order], "k--", lw=2, label="true f(x)"
    )
    _ = ax.plot(
        x[order], fitted_mean[order], color="C1", lw=2, label="fitted mu0 + s(x)"
    )
    _ = ax.fill_between(
        x[order],
        fitted_lo[order],
        fitted_hi[order],
        color="C1",
        alpha=0.2,
        label="95% credible band",
    )
    _ = ax.legend()
    _ = ax.set_xlabel("x")
    _ = ax.set_ylabel("y")
    _ = ax.set_title(f"Recovered smooth vs. truth (k={k}, m={m})\n {loo_r2}")
    fig.tight_layout()
    fig.savefig(save_path, dpi=150)
    plt.close(fig)


def diagnose_model(
    synthetic_dataset: pd.DataFrame,
    fit: FittedModel,
    uniformity: UniformityStats,
    lpv_stats: LpvStats,
    loo_diag: LooDiagnostics,
    dims: ModelDims,
    diagnostics_dir: Path,
    rng: np.random.Generator,
):
    """Emit diagnostics and calibration plots for a fitted model.

    Writes the synthetic dataset and model graph to `diagnostics_dir`,
    prints model summary and leave-one-out statistics, and renders prior
    predictive, energy, posterior predictive, fit-quality, and LOO-PIT
    plots (raw and coverage). All figures are saved as PNGs.

    Args:
        synthetic_dataset: The synthetic dataset used for fitting.
        fit: Fitted model with its inference data and associated artifacts.
        uniformity: Uniformity test results and entropy estimate.
        lpv_stats: LOO-PIT latent probability variable data.
        loo_diag: Leave-one-out diagnostics object.
        dims: Model dimension information.
        diagnostics_dir: Directory to write diagnostic figures to.
        rng: Random number generator for subsampling-based operations.
        fit: The fitted model, its inference data, and calibration figure.
        uniformity: LOO-PIT uniformity test results and entropy estimate.
        loo_diag: LOO-CV results and Pareto-k exceedance diagnostics.
        dims: Smoothing basis dimension and number of knots.
        diagnostics_dir: Directory to which the diagnostics are written.
        rng: Random generator for Monte Carlo simulation.

    Example:
        >>> diagnose_model(
                synthetic_dataset,
                FittedModel(model, idata, fig),
                UniformityCheck(ks_result, cvm_result, diff_entropy, rng),
                lpv_stats,
                loo_diag,
                ModelDims(m, k),
                diagnostics_dir,
                rng
        ... )

    """
    m, k = dims.m, dims.k

    synthetic_dataset.to_csv(diagnostics_dir / f"synthetic_dataset_m_{m}_k_{k}.csv")
    _ = fit.fig.figure.savefig(
        diagnostics_dir / f"paper_calibrated_model_m_{m}_k_{k}.png", dpi=150
    )
    g = pm.model_to_graphviz(fit.model)
    _ = g.render(
        diagnostics_dir / f"model_graph_m_{m}_k_{k}",
        format="png",
        cleanup=True,
    )
    _ = summary(fit.idata).to_csv(
        diagnostics_dir / f"model_summary_statistics_m_{m}_k_{k}.csv"
    )

    print(
        "Displaying the computed Pareto-smoothed importance sampling leave-one-out "
        + "cross-validation (PSIS-LOO-CV).\n"
    )
    print(loo_diag.elpd_data)
    mean_r2 = loo_diag.loo_rsquared.mean()
    hdi_lb, hdi_ub = hdi(loo_diag.loo_rsquared, prob=0.95)
    N = m * 50  # m samples in each 50 groups
    print(
        "Number of likely influential observations during PSIS-LOO-CV computation: "
        + f"{int(loo_diag.frac_k_above_good_k_psis * N)}."
    )
    print(
        "Number of likely influential observations during computing weighted "
        + "expectations using the PSIS-LOO-CV method computation: "
        + f"{int(loo_diag.frac_k_above_good_k_loo_exp * N)}."
    )
    print("Saving prior predictive plot ...")
    # Silence the prior predictive warning for this block
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message=".*observed_data.*")
        pc = azp.plot_ppc_dist(
            fit.idata,
            group="prior_predictive",
            kind="ecdf",
            visuals={
                "predictive_dist": {"color": "C1"},
                "observed_dist": {"color": "C3"},
            },
        )
        _ = pc.savefig(diagnostics_dir / f"prior_check_m_{m}_k_{k}.png", dpi=150)
    print("Saving energy plot ...")
    pc = azp.plot_energy(fit.idata, kind="ecdf")
    _ = pc.savefig(diagnostics_dir / f"plot_energy_m_{m}_k_{k}.png", dpi=150)
    print("Saving posterior predictive ...")
    pc = azp.plot_ppc_dist(fit.idata, kind="kde")
    _ = pc.savefig(diagnostics_dir / f"plot_ppc_dist_m_{m}_k_{k}.png", dpi=150)
    print("Saving posterior fit quality on training dataset ...")
    plot_fit_quality_check(
        synthetic_dataset,
        fit.idata,
        k=k,
        m=m,
        loo_r2=f"loo_R2(mean={mean_r2.mean():.4f}, hdi_lb={hdi_lb:.4f}, hdi_ub={hdi_ub:.4f})",
        save_path=diagnostics_dir / f"fit_curve_m_{m}_k_{k}.png",
    )
    # Two panels: LOO-PIT QQ plot (coverage=False) and LOO-PIT ETI coverage
    # plot (coverage=True), both rendered to image arrays.
    loo_pit_img, loo_eti_img = [
        _render_pc_to_img(
            _create_loo_pit_plot(
                lpv_stats.lpv_ds, coverage=coverage, ci_level=0.95, figure_size=(7, 4)
            )
        )
        for coverage in (False, True)
    ]
    print("Saving loo pit plot ...")
    plt.imsave(diagnostics_dir / f"plot_loo_pit_m_{m}_k_{k}.png", loo_pit_img)
    print("Saving loo pit plot coverage ...")
    plt.imsave(diagnostics_dir / f"plot_loo_pit_coverage_m_{m}_k_{k}.png", loo_eti_img)
    print("Saving loo pit histogram ...")
    hist_fig = plot_pit_hist(lpv_stats.lpv_da.to_numpy())
    hist_fig.savefig(
        diagnostics_dir / f"plot_loo_pit_histogram_m_{m}_k_{k}.png", dpi=150
    )
    plt.close("all")
    print(
        f"\nKolmogorov-Smirnov test for goodness of uniformity: {uniformity.ks_result}"
    )
    print(
        f"\none-sample Cramér-von Mises for goodness of uniformity: {uniformity.cvm_result}"
    )

    z_score, percentile, expected_entropy = entropy_uniformity_z_score(
        rng, n=N, observed_entropy=uniformity.diff_entropy
    )
    print(
        f"\nThe Expected entropy for perfect uniform data (N={N}): "
        + f"{expected_entropy:.4f} nats while the Estimated differential entropy from "
        + f"uniformity: {uniformity.diff_entropy:.4f} with the Z-score: {z_score:+.2f}. "
        + f"Note {percentile}% of simulations had lower entropy than the entropy of "
        + "the model posterior PIT distribution."
    )


# Cache of pre-built models keyed by (k, m, G). Since the model graph
# (coords, shapes, basis dimension, number of groups) is fixed across all
# simulations for a given (k, m) combination, we build it once per worker
# process and swap data via model.set_data() — avoiding repeated PyTensor
# graph construction and coordinate setup.
_model_cache: dict[tuple[int, int, int], pm.Model] = {}


def _get_or_build_model(k: int, m: int, G: int = 50) -> pm.Model:
    key = (k, m, G)
    if key not in _model_cache:
        params = DGPParams(G=G, m=m, sigma=1 / 3)
        rng = np.random.default_rng(0)
        dummy = generate_dataset(params, rng)
        _model_cache[key] = build_model(dummy, k=k)
    return _model_cache[key]


def _fit_model(
    k: int,
    m: int,
    B: np.ndarray,
    group_idx: np.ndarray,
    y: np.ndarray,
    chains: int,
    draws: int,
    seed: int,
) -> ModelFit:
    """Attach data to the cached model, sample, and count free parameters.

    Reuses the cached model graph for the given (k, m, G) combination by
    swapping in the new data containers, then draws prior, posterior, and
    posterior-predictive samples and computes the log likelihood.

    Args:
        k: Number of knots.
        m: Smoothing basis dimension.
        B: Covariate matrix to attach to the model.
        group_idx: Group index array to attach to the model.
        y: Observed outcomes to attach to the model.
        chains: Number of MCMC chains to sample.
        draws: Number of draws per chain.
        seed: Random seed for sampling.

    Returns:
        The fitted model, its inference data tree, and the number of free
        parameters.

    Example:
        >>> fit = _fit_model(
        ...     k=12,
        ...     m=4,
        ...     B=B,
        ...     group_idx=group_idx,
        ...     y=y,
        ...     chains=2,
        ...     draws=500,
        ...     seed=42,
        ... )

    """
    model = _get_or_build_model(k, m, G=50)

    with model:
        model.set_data("B", B)
        model.set_data("group_idx", group_idx)
        model.set_data("y_obs_data", y)

        idata = pm.sample(
            draws=draws,
            chains=chains,
            cores=4,
            target_accept=0.95,
            random_seed=seed,
            progressbar=False,
        )
        prior = pm.sample_prior_predictive(random_seed=seed)
        idata.update(prior)
        _ = pm.sample_posterior_predictive(
            idata, extend_inferencedata=True, progressbar=False, random_seed=seed
        )
        _ = pm.compute_log_likelihood(idata, progressbar=False)
        n_params = sum(rv.size.eval() for rv in model.free_RVs)

    return ModelFit(model=model, idata=idata, n_params=n_params)


def _compute_loo_diagnostics(
    idata: DataTree, chains: int, draws: int, rng: np.random.Generator
) -> LooDiagnostics:
    """Compute LOO-CV and Pareto-k exceedance fractions (PSIS and LOO-expectation).

    Args:
        idata: Inference data tree with log-likelihood computed.
        chains: Number of MCMC chains used for the fit.
        draws: Number of draws per chain used for the fit.
        rng: Random generator to compute LOO-adjusted R-squared using
            Dirichlet-weighted bootstrap.

    Returns:
        Leave-one-out diagnostics with PSIS and LOO-expectation Pareto-k
        exceedance fractions.

    Example:
        >>> diags = _compute_loo_diagnostics(idata, chains=2, draws=500)

    """
    # ignore the generic warning but display explicitly the severity of warning
    # through `frac_psis` and `frac_loo_exp`
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            category=UserWarning,
            message=".*You should consider using a more robust model, *",
        )
        elpd_data = cast(ELPDData, loo(idata, pointwise=True))
        ypred_loo, func_specific_khat = loo_expectations(
            idata, log_weights=elpd_data.log_weights, pareto_k=elpd_data.pareto_k
        )

    var_name = _resolve_likelihood_var_name(idata)
    y_obs_da = idata.observed_data[var_name]
    loo_rsquared = y_obs_da.azstats.loo_r2(ypred_loo=ypred_loo, random_state=rng)
    _, good_k_loo_exp = _warn_pareto_k(
        func_specific_khat, chains * draws, suppress=True
    )

    frac_psis = float(np.mean(elpd_data.pareto_k.to_numpy() > elpd_data.good_k))
    frac_loo_exp = float(np.mean(func_specific_khat.to_numpy() > good_k_loo_exp))

    return LooDiagnostics(
        elpd_data=elpd_data,
        ypred_loo=ypred_loo,
        loo_rsquared=loo_rsquared,
        frac_k_above_good_k_psis=frac_psis,
        frac_k_above_good_k_loo_exp=frac_loo_exp,
    )


def _compute_calibration(
    idata: DataTree, loo_diag: LooDiagnostics, seed: int
) -> CalibrationResult:
    """Compute LOO R-squared, p-values, and the calibration curve/figure.

    Args:
        idata: Inference data tree with observed data and posterior
            predictive draws.
        loo_diag: Leave-one-out diagnostics with expectations and weights.
        seed: Random seed for the calibration curve plot.

    Returns:
        The calibration figure and its statistics.

    Example:
        >>> calib = _compute_calibration(idata, loo_diag, seed=42)

    """
    calib_fig, calib_stats = plot_loo_calibration_curve_with_reference(
        idata=idata,
        weights=cast(DataArray, cast(object, np.exp(loo_diag.elpd_data.log_weights))),
        random_seed=seed,
    )

    return CalibrationResult(fig=calib_fig, stats=calib_stats)


def _assemble_result(
    sim: int,
    fit: ModelFit,
    loo_diag: LooDiagnostics,
    calib: CalibrationResult,
    uniformity: UniformityStats,
) -> SimulationResult:
    """Collect all metrics into the final result dict.

    Args:
        sim: Simulation index.
        fit: Fitted model with its inference data and parameter count.
        loo_diag: Leave-one-out diagnostics.
        calib: Calibration figure, statistics, and p-values.
        uniformity: Uniformity test results and entropy estimate.

    Returns:
        The metrics for this simulation.

    Example:
        >>> result = _assemble_result(
        ...     sim=0,
        ...     fit=fit,
        ...     loo_diag=loo_diag,
        ...     calib=calib,
        ...     uniformity=uniformity,
        ... )

    """
    return {
        "sim": int(sim),
        "model_params": int(fit.n_params),
        "model_eff_params": float(loo_diag.elpd_data.p),
        "elpd": float(loo_diag.elpd_data.elpd),
        "loo_rsquared": float(loo_diag.loo_rsquared.mean()),
        "frac_k_above_good_k_psis": float(loo_diag.frac_k_above_good_k_psis),
        "frac_k_above_good_k_loo_exp": float(loo_diag.frac_k_above_good_k_loo_exp),
        "n_miscalibrated": int(calib.stats.n_miscalibrated),
        "calibration_error": float(calib.stats.calibration_error),
        "weighted_cal_error": float(calib.stats.weighted_cal_error),
        "ks_pvalue": float(uniformity.ks_result.pvalue),
        "ks_stat": float(uniformity.ks_result.statistic),
        "cvm_pvalue": float(uniformity.cvm_result.pvalue),
        "cvm_stat": float(uniformity.cvm_result.statistic),
        "diff_entropy": float(uniformity.diff_entropy),
        "p_val_az": float(uniformity.p_val_az),
        "p_val_coverage_az": float(uniformity.p_val_coverage_az),
    }


def run_one_simulation(
    sim: int,
    m: int,
    k: int,
    RNG_SEED: int,
    chains: int = 4,
    draws: int = 2500,
    verbose: bool = False,
    diagnostics_dir: Path = DIAGNOSTICS_DIR,
) -> SimulationResult:
    """Run one full simulation trial and return calibration metrics.

    Generates a dataset, fits the Bayesian spline model, and computes
    LOO-based predictive checks: Pareto-k diagnostics, LOO R-squared,
    uniformity tests on LOO-PIT values, and calibration-curve statistics.

    Args:
        sim: Simulation trial index; seeds the RNG as RNG_SEED + sim.
        m: Observations per group.
        k: Spline basis dimension of the fitted model.
        RNG_SEED: Base random seed for sampling and data generation.
        chains: Number of MCMC chains. Defaults to 4.
        draws: Number of draws per chain. Defaults to 2500.
        verbose: If True, write diagnostic plots to diagnostics_dir.
            Defaults to False.
        diagnostics_dir: Directory for diagnostic plots. Defaults to DIAGNOSTICS_DIR.

    Returns:
        A SimulationResult dict of metrics and p-values keyed by name,
        including elpd, loo_rsquared, Pareto-k exceedance fractions,
        calibration error, and uniformity-test statistics for LOO-PIT.

    Example:
    ```python
        result = run_one_simulation(sim=0, m=10, k=12, RNG_SEED=42)
        print(result["elpd"], result["ks_pvalue"])
    ```

    """
    seed = RNG_SEED + sim
    params = DGPParams(G=50, m=m, sigma=1 / 3)
    rng = np.random.default_rng(seed)

    d = generate_dataset(params, rng)
    B = build_spline_basis(d["x"].to_numpy(), k=k)
    group_idx, _ = d["group"].factorize()
    y = d["y"].to_numpy()

    fit = _fit_model(k, m, B, group_idx, y, chains, draws, seed)
    loo_diag = _compute_loo_diagnostics(fit.idata, chains, draws, rng)
    calib = _compute_calibration(fit.idata, loo_diag, seed)
    uniformity, lpv_stats = compute_loo_pit_uniformity_stats(
        calib.stats.loo_pit.to_numpy(), fit.idata, rng, loo_diag=None
    )

    if verbose:
        assert diagnostics_dir.exists(), "Diagnostics directory path is not provided!"
        diagnose_model(
            d,
            FittedModel(fit.model, fit.idata, calib.fig),
            UniformityStats(
                uniformity.ks_result,
                uniformity.cvm_result,
                uniformity.diff_entropy,
                uniformity.p_val_az,
                uniformity.p_val_coverage_az,
            ),
            lpv_stats,
            loo_diag,
            ModelDims(m, k),
            diagnostics_dir,
            rng,
        )
    plt.close(calib.fig.figure)

    return _assemble_result(sim, fit, loo_diag, calib, uniformity)


if __name__ == "__main__":
    verbose = False
    RNG_SEED = 110
    K_M_COMBINATIONS = [
        (48, 10),
        (24, 10),
        (6, 10),
        (12, 5),
        (12, 10),
        (12, 15),
    ]

    if verbose:
        for k, m in K_M_COMBINATIONS:
            print(f"\n{'=' * 60}\nDiagnostic run: k={k}, m={m}\n{'=' * 60}")
            _ = run_one_simulation(sim=0, m=m, k=k, RNG_SEED=RNG_SEED, verbose=verbose)
        print(f"\nDone — diagnostic artifacts saved to {DIAGNOSTICS_DIR}")
        sys.exit(0)

    # Re-exec under systemd-inhibit to block suspend, but allow display to
    # turn off (--what=sleep only inhibits sleep, not screen blanking).
    with InhibitSleep("Running compressor_fouling_modeling simulations"):
        pass

    N_SIMULATIONS = 2500
    cpu_s = os.cpu_count()
    cpus = cpu_s if cpu_s is not None else 4
    N_JOBS = max(1, cpus // 2)
    SAVE_EVERY = 100

    with LogTime(f"{N_SIMULATIONS} simulations"):
        for k, m in K_M_COMBINATIONS:
            tag = f"m_{m}_k_{k}"
            print(
                f"\n{'=' * 60}\nRunning {tag} ({N_SIMULATIONS} simulations)\n{'=' * 60}"
            )

            fn = partial(run_one_simulation, m=m, k=k, RNG_SEED=RNG_SEED)
            results = []
            parquet_path = CALIB_SIM_RES_DIR / f"df_results_{tag}.parquet.gzip"
            partial_path = CALIB_SIM_RES_DIR / f"df_results_{tag}_partial.parquet.gzip"

            with tqdm(total=N_SIMULATIONS, desc=tag) as pbar:
                for result in Parallel(n_jobs=N_JOBS, return_as="generator_unordered")(
                    delayed(fn)(sim) for sim in range(N_SIMULATIONS)
                ):
                    results.append(result)
                    _ = pbar.update()
                    if len(results) % SAVE_EVERY == 0:
                        pd.DataFrame(results).to_parquet(
                            partial_path, compression="gzip"
                        )

            df_results = pd.DataFrame(results)
            df_results.to_parquet(parquet_path, compression="gzip")
            if partial_path.exists():
                partial_path.unlink()
            print(f"\nSaved {parquet_path} ({len(df_results)} rows).")
